/*
 * Copyright (c) 2019, ETH Zurich.
 * Copyright (c) 2022, The University of British Columbia.
 * All rights reserved.
 *
 * This file is distributed under the terms in the attached LICENSE file.
 * If you do not find this file, copies can be found by writing to:
 * ETH Zurich D-INFK, Universitaetstrasse 6, CH-8092 Zurich. Attn: Systems Group.
 */

///////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                               //
//                   !! WARNING !!   DO NOT EDIT THIS FILE   !! WARNING !!                       //
//                                                                                               //
//      This file is part of the grading library and will be overwritten before grading.         //
//              To ensure tests are run correctly, do not edit this file                         //
//                                                                                               //
///////////////////////////////////////////////////////////////////////////////////////////////////

#include <stdio.h>

#include <aos/aos.h>
#include <aos/capabilities.h>
#include <aos/ram_alloc.h>
#include <aos/aos_rpc.h>

#include <spawn/spawn.h>

#include <grading/grading.h>
#include <grading/io.h>
#include <grading/state.h>
#include <grading/options.h>
#include <grading/tests.h>


/*
 * ===============================================================================================
 * Grading Hooks
 * ===============================================================================================
 *
 * These functions will be called by init to configure and trigger the grading tests to be run.
 * Usually, it should be fine if you leave them as-is, and we generally overwrite this file as
 * per warning above. However, depending on your implementation, some of your tests may need
 * to be run a bit later as they may require more of the system to be initialized. In that case,
 * please adapt the grading hooks to ensure the tests we provided to you run correctly.
 */


void grading_setup_bsp_init(int argc, char **argv)
{
    grading_proc_name    = "init";
    grading_argc         = argc;
    grading_argv         = argv;
    grading_argument_src = GRADING_ARG_SRC_CMDLINE;
}

void grading_setup_app_init(struct bootinfo *bi)
{
    if (bi == NULL) {
        USER_PANIC("no bootinfo setup\n");
    }
    grading_proc_name    = "init";
    grading_bootinfo     = bi;
    grading_argument_src = GRADING_ARG_SRC_BI;
}

void grading_setup_noninit(int *argc, char ***argv)
{
    // TODO: Filter arguments
    grading_argc         = *argc;
    grading_argv         = *argv;
    grading_argument_src = GRADING_ARG_SRC_ARGV;
}

void grading_test_mm(struct mm *test)
{
    grading_printf("reached grading_test_mm.\n");

    grading_parse_arguments();
    grading_run_tests_physical_memory(test);
}

void grading_test_early(void)
{
    grading_printf("reached grading_test_early.\n");

    grading_parse_arguments();
    grading_run_tests_virtual_memory(true);
}

void grading_test_late(void)
{
    grading_printf("reached grading_test_late.\n");

    grading_run_tests_virtual_memory(false);
    grading_run_tests_processes();
    grading_run_tests_rpc();
    grading_run_tests_multicore();
    grading_run_tests_urpc();
}
