/*
 * Copyright (c) 2016, ETH Zurich.
 * All rights reserved.
 *
 * This file is distributed under the terms in the attached LICENSE file.
 * If you do not find this file, copies can be found by writing to:
 * ETH Zurich D-INFK, Universitaetstrasse 6, CH-8092 Zurich. Attn: Systems Group.
 */


///////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                               //
//                   !! WARNING !!   DO NOT EDIT THIS FILE   !! WARNING !!                       //
//                                                                                               //
//      This file is part of the grading library and will be overwritten before grading.         //
//              To ensure tests are run correctly, do not edit this file                         //
//                                                                                               //
///////////////////////////////////////////////////////////////////////////////////////////////////

#include <stdio.h>

#include <aos/aos.h>
#include <aos/solution.h>

#include <grading/grading.h>

#include <grading/io.h>
#include <grading/options.h>
#include <grading/options_internal.h>


bool grading_handle_arg(struct grading_options *opts, const char *arg)
{
    /* We only recognise opts starting with "t:" */
    if (!strncmp(arg, "t:", 2)) {
        arg = arg + 2;
        if (!strncmp(arg, "m1", 2)) {
            return grading_opts_handle_m1_tests(opts, arg + 2);
        } else if (!strncmp(arg, "m2", 2)) {
            return grading_opts_handle_m2_tests(opts, arg + 2);
        } else if (!strncmp(arg, "m3", 2)) {
            return grading_opts_handle_m3_tests(opts, arg + 2);
        } else if (!strncmp(arg, "m4", 2)) {
            return grading_opts_handle_m4_tests(opts, arg + 2);
        } else if (!strncmp(arg, "m5", 2)) {
            return grading_opts_handle_m5_tests(opts, arg + 2);
        } else if (!strncmp(arg, "m6", 2)) {
            return grading_opts_handle_m6_tests(opts, arg + 2);
        } else {
            grading_printf("Unrecognised grading option: \"t:%s\"\n", arg);
            return false;
        }
    }
    return false;
}
