/*
 * Copyright (c) 2019, ETH Zurich.
 * Copyright (c) 2022, The University of British Columbia.
 * All rights reserved.
 *
 * This file is distributed under the terms in the attached LICENSE file.
 * If you do not find this file, copies can be found by writing to:
 * ETH Zurich D-INFK, Universitaetstrasse 6, CH-8092 Zurich. Attn: Systems Group.
 */

///////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                               //
//                   !! WARNING !!   DO NOT EDIT THIS FILE   !! WARNING !!                       //
//                                                                                               //
//      This file is part of the grading library and will be overwritten before grading.         //
//              To ensure tests are run correctly, do not edit this file                         //
//                                                                                               //
///////////////////////////////////////////////////////////////////////////////////////////////////

#include <stdlib.h>
#include <stdio.h>
#include <time.h>

#include <aos/aos.h>

#include <proc_mgmt/proc_mgmt.h>

#include <grading/io.h>
#include <grading/options.h>
#include <grading/state.h>

// errval_t grading_utils_do_spawn_test(char *lbl, coreid_t core)
// {
//     errval_t err;
//     char    *binary = grading_options.m7_fs_options.named.binary;

//     grading_printf("do_spawn_test(%d, %s)\n", core, binary);

//     domainid_t pid;
//     err = proc_mgmt_spawn_program(binary, core, &pid);
//     if (err_is_fail(err)) {
//         grading_test_fail(lbl, "failed to load: %s\n", err_getstring(err));
//         return err_push(err, SPAWN_ERR_LOAD);
//     }

//     // looking for this one could be tricky w.r.t. interleaving
//     grading_test_pass(lbl, "spawned process\n");

//     return SYS_ERR_OK;
// }